﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 
namespace SystemBase
{
    using JMS;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    
    
    [InvokerInfo("ConfigServiceAPI")]
    public class ConfigServiceAPI : IImplInvoker
    {
        
        protected JMS.IMicroService _microService;
        
        public ConfigServiceAPI(JMS.IMicroService microService)
        {
            this._microService = microService;
        }
        
        public virtual string GetReferenceServiceByServiceName(string Namespace)
        {
            return this._microService.Invoke<string>("GetReferenceServiceByServiceName", Namespace);
        }
        
        public virtual Task<string> GetReferenceServiceByServiceNameAsync(string Namespace)
        {
            return this._microService.InvokeAsync<string>("GetReferenceServiceByServiceName", Namespace);
        }
        
        public virtual string RegisterInfo(string value)
        {
            return this._microService.Invoke<string>("RegisterInfo", value);
        }
        
        public virtual Task<string> RegisterInfoAsync(string value)
        {
            return this._microService.InvokeAsync<string>("RegisterInfo", value);
        }
    }
}
